FROM nginx:latest

# Copy the frontend code into the container
COPY index.html /usr/share/nginx/html

# Configure Nginx (optional, if you need any custom configurations)
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default HTTP port
EXPOSE 80

